baseURL = "https://c653labs.com"
languageCode = "en-us"
title = "C653 Labs"
theme = "aerial"
googleAnalytics = "UA-102144354-1"

[params]
  name = "C653 Labs"
  about = "Software and Devops consulting. Contact us today."

[[params.social]]
  medium = "GitHub"
  icon = "github"
  link = "https://github.com/c653labs"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:contact@c653labs.com"
